name: "🦍 Run Lazy Apes Bot"
 name: "🐵 Run Lazy Apes Bot"

-on:
-  schedule:
-    - cron: '*/2 * * * *'   # every 2 minutes
+on:
+  workflow_dispatch:       # ← enables “Run workflow” button
+  schedule:
+    - cron: '*/2 * * * *'   # every 2 minutes


on:
  schedule:
    - cron: '*/2 * * * *'   # every 2 minutes

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install deps & Run Bot
        env:
          OPENSEA_API_KEY:        ${{ secrets.OPENSEA_API_KEY }}
          COLLECTION_SLUG:        ${{ secrets.COLLECTION_SLUG }}
          TWITTER_API_KEY:        ${{ secrets.TWITTER_API_KEY }}
          TWITTER_API_KEY_SECRET: ${{ secrets.TWITTER_API_KEY_SECRET }}
          TWITTER_ACCESS_TOKEN:   ${{ secrets.TWITTER_ACCESS_TOKEN }}
          TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
        run: |
          npm ci
          node bot.js
